"""Hand-authored synthetic Italian parent messages for the symptom-extraction
test set. Author: Claude (Opus 4.7).

Structure:
    POSITIVES[symptom] -> list[str]   each message clearly contains symptom
    NEGATIONS[symptom] -> list[str]   each message explicitly NEGATES symptom
    PAST_RESOLVED      -> list[(message, resolved_symptom)]
    MULTI              -> list[(message, [symptoms])]

Style: WhatsApp/email genitore -> pediatra. Colloquiale, senza saluti.
Età variabili. Sinonimi e perifrasi tipiche italiane.
"""

# ----------------------------------------------------------------------------
# POSITIVES: 4 per symptom (81 * 4 = 324 cases)
# ----------------------------------------------------------------------------
POSITIVES: dict[str, list[str]] = {
    "Febbre": [
        "Da stamattina Marco scotta tantissimo, il termometro segna 39.2 e ha le guance rosse fuoco.",
        "La piccola di 8 mesi è bollente al tatto, sento la fronte caldissima e ha brividi sotto la coperta.",
        "Mio figlio di 5 anni ha 38.5 da ieri sera, gli ho dato la tachipirina ma risale dopo poche ore.",
        "L'adolescente ha temperatura alta da tre giorni, oscilla tra 38 e 39, è abbattuto e dorme tanto.",
    ],
    "Mal di gola": [
        "Lucia di 6 anni dice che le fa male la gola quando deglutisce, quasi non riesce a mangiare.",
        "Il bambino si tocca continuamente il collo e si lamenta che fa male a inghiottire l'acqua.",
        "Mia figlia di 11 anni ha la gola arrossata e dolente, parla con voce strana e rifiuta i cibi solidi.",
        "Da due giorni non vuole mangiare perché dice che la gola brucia, le ho guardato dentro ed è tutto rosso.",
    ],
    "Dolore addominale": [
        "Tommaso di 4 anni si tiene la pancia e piange, dice che gli fa male qua sotto l'ombelico.",
        "Mia figlia continua a lamentarsi di dolori alla pancia da stamattina, viene a ondate ogni 20 minuti.",
        "Il piccolo si rotola sul letto stringendosi lo stomaco, dice che è un dolore forte alla pancia.",
        "Da ieri sera mio figlio di 9 anni ha mal di pancia continuo, non si trova posizione comoda.",
    ],
    "Vomito": [
        "Sofia ha vomitato 4 volte da stamattina, anche solo l'acqua le torna su.",
        "Il bambino di 2 anni ha rimesso tutto quello che ha mangiato a pranzo, anche il latte.",
        "Mio figlio di 7 anni ha vomitato due volte stanotte, getto verde-giallastro.",
        "Continua a vomitare ogni ora, ormai esce solo bile, sono molto preoccupata.",
    ],
    "Diarrea": [
        "Aida di 4 mesi ha avuto tre scariche liquide in mezz'ora, pannolino tutto bagnato.",
        "Mio figlio di 5 anni ha la diarrea da ieri, feci molto liquide e maleodoranti, va in bagno ogni ora.",
        "La bambina ha scariche acquose continue da stanotte, sembra disidratata e ha labbra secche.",
        "Da due giorni il piccolo fa la cacca tutta liquida, oggi siamo già a 6 scariche.",
    ],
    "Difficoltà respiratoria": [
        "Sento mio figlio respirare a fatica, le narici si dilatano e tira proprio in dentro la pancia.",
        "Il bambino respira veloce e affannato, si sente un fischio quando butta fuori l'aria.",
        "Mia figlia di 3 anni fa fatica a respirare, vedo i muscoli del collo che si tirano ad ogni respiro.",
        "Da poco respira male, quasi ansima, e ha le labbra che mi sembrano un po' bluastre.",
    ],
    "Tosse": [
        "Davide tossisce da tre giorni, una tosse secca insistente che peggiora di notte.",
        "La piccola ha la tosse grassa con tanto catarro, sento i bronchi pieni quando la tengo in braccio.",
        "Mio figlio di 6 anni ha attacchi di tosse forti, tipo abbaio, soprattutto verso sera.",
        "L'adolescente tossisce continuamente da una settimana, gli viene da vomitare quando tossisce.",
    ],
    "Naso ostruito o che cola": [
        "Pietro ha il naso completamente chiuso, dorme con la bocca aperta e russa.",
        "Da due giorni le cola il naso continuamente, muco trasparente che le scende sul labbro.",
        "Il bambino di 1 anno ha il nasino tappato e fa fatica a poppare, si stacca per respirare.",
        "Mia figlia ha il raffreddore forte, naso che cola con muco verdastro e occhi gonfi.",
    ],
    "Mal di orecchio": [
        "Si sveglia di notte piangendo e si tocca continuamente l'orecchio destro, dice che fa male.",
        "Mio figlio di 3 anni urla che gli fa male l'orecchio, non vuole appoggiarci la testa.",
        "Da ieri si lamenta di un dolore forte all'orecchio sinistro, dice che pulsa.",
        "Il piccolo piange quando lo metto sdraiato, mi indica l'orecchio e dice 'bua'.",
    ],
    "Occhio rosso": [
        "Tiberio ha l'occhio destro tutto rosso da stamattina, sembra una congiuntivite.",
        "L'occhio sinistro di mia figlia è arrossato e lei si lamenta che le da fastidio la luce.",
        "Da ieri ha entrambi gli occhi iniettati di sangue, tipo arrossamento diffuso.",
        "Il bambino ha l'occhio molto rosso, continua a strofinarsi e dice che brucia.",
    ],
    "Secrezioni oculari": [
        "Stamattina mio figlio non riusciva ad aprire l'occhio, era tutto incollato di pus giallo.",
        "Le esce una sostanza appiccicosa dall'occhio destro, dura tutto il giorno.",
        "La bambina ha le ciglia incollate al risveglio per via di tutto il muco giallastro.",
        "Continua a colargli liquido bianco-giallo dall'occhio, devo pulirlo ogni ora.",
    ],
    "Occhio gonfio": [
        "Mio figlio si è svegliato con la palpebra destra gonfissima, sembra una pallina.",
        "L'occhio sinistro è gonfio e tirato, fatica ad aprirlo del tutto.",
        "Da stanotte ha la palpebra superiore gonfia, calda al tatto e dolente.",
        "La bambina ha entrambi gli occhi gonfi, le palpebre sembrano cuscinetti.",
    ],
    "Trauma cranico": [
        "Mio figlio è caduto dal seggiolone e ha battuto la testa con un tonfo forte sul pavimento.",
        "La piccola è scivolata in bagno e ha picchiato la nuca, ora ha un bernoccolo grosso.",
        "Tommaso giocando ha sbattuto la fronte contro lo spigolo del tavolo, c'è stato un botto secco.",
        "Si è rovesciato all'indietro col triciclo battendo violentemente la testa, piangeva tantissimo.",
    ],
    "Mal di testa": [
        "Mia figlia di 10 anni si lamenta di mal di testa forte da due giorni, soprattutto sulle tempie.",
        "Il bambino dice che gli fa male la testa, indica la fronte e vuole stare al buio.",
        "Da stamattina ha un cerchio alla testa che non passa, peggiora se si muove.",
        "L'adolescente ha mal di testa pulsante ogni pomeriggio dopo la scuola.",
    ],
    "Lesioni cutanee": [
        "Sono comparse delle bollicine rosse sulla pancia e sulla schiena di Francesco.",
        "Mia figlia ha delle macchie strane sulle braccia, tipo placche rosse in rilievo.",
        "Da stamattina ha tantissime macchioline rosse sparse su tutto il corpo, alcune con la punta bianca.",
        "Sono uscite delle vescicole sulle gambe del bambino, alcune sono già scoppiate.",
    ],
    "Dolore all'occhio": [
        "Lucia si lamenta di un dolore forte all'occhio sinistro da quando si è svegliata.",
        "Il bambino dice che gli fa male l'occhio, chiude la palpebra e non vuole aprirla.",
        "Da ieri sera ha dolore all'occhio destro, dice che è un dolore profondo e pungente.",
        "Mia figlia di 8 anni ha male all'occhio quando lo muove, soprattutto guardando in alto.",
    ],
    "Ingestione sostanza tossica": [
        "Ho appena trovato il bambino con la bottiglia del detersivo aperta, temo abbia bevuto un sorso.",
        "Mia figlia di 2 anni ha ingoiato delle pastiglie del nonno, non so quante.",
        "Il piccolo ha ingerito del candeggiante che era in un bicchiere, quanto ne ho da capire.",
        "Sospetto che mio figlio abbia bevuto dell'antigelo, era nel garage e ne è rimasto poco.",
    ],
    "Stipsi": [
        "Mio figlio di 4 anni non fa la cacca da 5 giorni e si lamenta quando ci prova.",
        "La bambina è stitica da una settimana, le feci quando escono sono dure come palline.",
        "Tommaso da giorni non riesce ad andare in bagno, piange e si tiene quando deve provarci.",
        "Da due settimane fa la cacca solo ogni 4-5 giorni e con grande sforzo.",
    ],
    "Dolore o bruciore nella minzione": [
        "Mia figlia di 6 anni piange ogni volta che fa pipì, dice che brucia tantissimo.",
        "Il bambino si lamenta di bruciore quando urina, si stringe e fa fatica.",
        "Da ieri quando va in bagno strilla, dice che le pizzica forte mentre fa la pipì.",
        "L'adolescente lamenta dolore alla fine della minzione, accompagnato da bruciore.",
    ],
    "Insonnia": [
        "Da una settimana mio figlio non riesce ad addormentarsi, sta sveglio fino alle due di notte.",
        "La bambina di 7 anni fa fatica a prendere sonno, si rigira nel letto per ore.",
        "Mio figlio è cambiato, ormai ogni sera ci mette ore prima di addormentarsi anche se è stanchissimo.",
        "Da quando è iniziata la scuola non dorme più, resta sveglio nel letto fino a tardi.",
    ],
    "Risvegli notturni": [
        "Mio figlio si sveglia 4-5 volte ogni notte chiamandomi, poi non riparte a dormire.",
        "Da qualche settimana dorme a pezzi, ogni due ore si sveglia piangendo.",
        "La bambina si sveglia di soprassalto più volte a notte, sembra disorientata.",
        "Il piccolo non fa più una notte intera, si sveglia continuamente e vuole il latte.",
    ],
    "Russamento nel sonno": [
        "Quando dorme fa un rumore forte tipo un adulto che russa, si sente da fuori la stanza.",
        "Mio figlio di 5 anni russa fortissimo ogni notte, sembra un trattorino.",
        "La bambina russa da quando è raffreddata ma ora il rumore è continuo e profondo.",
        "Sento il piccolo russare in modo molto rumoroso, il petto gli vibra.",
    ],
    "Sonnambulismo": [
        "Stanotte si è alzato e camminava per casa con gli occhi aperti ma senza riconoscermi.",
        "Mia figlia di 8 anni si alza nel sonno e fa il giro delle stanze, poi torna a letto e non ricorda nulla.",
        "Il bambino la notte cammina nel sonno, una volta lo abbiamo trovato in cucina.",
        "Da qualche settimana succede che si alzi dal letto dormendo e parli a vuoto.",
    ],
    "Apnee nel sonno": [
        "Mentre dorme mi sembra che a tratti smetta proprio di respirare, poi fa un respirone grosso.",
        "Russa, però ogni tanto il rumore si ferma del tutto per alcuni secondi e poi riprende.",
        "Ho notato che il bambino fa pause nel respiro durante il sonno, conto anche 10 secondi.",
        "Mio figlio interrompe il respiro nel sonno e poi riparte di scatto come boccheggiando.",
    ],
    "Bruxismo": [
        "Mia figlia di notte digrigna i denti, si sente un rumore fortissimo dalla camera accanto.",
        "Il bambino stringe i denti nel sonno, sembra li grattugi tra loro.",
        "Da qualche mese sento mio figlio masticare i denti durante la notte.",
        "L'adolescente al risveglio si lamenta che gli fa male la mascella, di notte digrigna.",
    ],
    "Inappetenza": [
        "Mio figlio da una settimana non vuole mangiare niente, rifiuta anche i piatti preferiti.",
        "La bambina ha perso completamente l'appetito, si siede a tavola e non tocca cibo.",
        "Da giorni il piccolo mangia pochissimo, appena due cucchiai poi spinge via il piatto.",
        "Tommaso si rifiuta di mangiare, anche piatti che adorava ora li respinge.",
    ],
    "Iperfagia": [
        "Da qualche settimana mio figlio mangia in continuazione, ha sempre fame anche dopo i pasti.",
        "La bambina vuole mangiare ogni ora, non si sazia mai e chiede sempre cibo.",
        "Il piccolo divora porzioni doppie e poi piange perché vuole ancora.",
        "Mio figlio mangia il triplo del solito, ho notato un appetito esagerato negli ultimi giorni.",
    ],
    "Polidipsia": [
        "Beve litri di acqua durante il giorno, vuota la bottiglia in continuazione.",
        "Mio figlio chiede da bere ogni cinque minuti, sembra non riuscire a togliersi la sete.",
        "La bambina ha sempre sete, beve enormi quantità di acqua e succo.",
        "Da qualche giorno il piccolo non smette di bere, si attacca al rubinetto.",
    ],
    "Convulsioni": [
        "Mio figlio ha avuto un attacco con scosse a tutto il corpo, ha perso conoscenza per due minuti.",
        "Improvvisamente la bambina si è irrigidita e ha iniziato a tremare a scatti, occhi rovesciati.",
        "Il piccolo ha avuto le convulsioni, scosse ritmiche di braccia e gambe per oltre un minuto.",
        "Tommaso si è messo a tremare in modo strano, irrigidito, schiumava un po' dalla bocca.",
    ],
    "Nausea": [
        "Mia figlia non ha vomitato ma da stamattina si sente la nausea, deglutisce in continuazione.",
        "Il bambino dice che gli viene su lo stomaco ma non ha rimesso, è pallido e suda.",
        "Da poco si lamenta che ha la nausea, ha il viso pallido e fa facce strane.",
        "Tommaso dice che gli gira lo stomaco e ha voglia di vomitare ma non ci riesce.",
    ],
    "Lesioni del cavo orale": [
        "Mia figlia ha delle afte bianche sulla lingua e dentro le guance, le fanno male a mangiare.",
        "Sono comparse delle ulcerine in bocca al bambino, sulla lingua ce ne sono almeno tre.",
        "Il piccolo ha vesciche dolorose all'interno delle labbra, fatica a mangiare.",
        "Mio figlio ha tante macchioline bianche sul palato, dice che bruciano tantissimo.",
    ],
    "Sanguinamento dal naso": [
        "Mio figlio ha avuto due epistassi questa mattina, sangue dal naso senza motivo.",
        "Da stanotte le esce sangue dal naso ogni volta che si soffia, si è già macchiata il pigiama.",
        "Il bambino ha sanguinato dal naso per dieci minuti, non si fermava nemmeno comprimendo.",
        "Tommaso ha perso sangue dal naso tre volte oggi, sempre la narice destra.",
    ],
    "Irrequietezza o pianto inconsolabile": [
        "Il piccolo di 3 mesi piange senza sosta da due ore, non si calma con niente.",
        "Mia figlia è inconsolabile da tutto il pomeriggio, urla e si dimena, niente funziona.",
        "Il neonato è agitatissimo, piange di continuo, lo allatto e non si calma comunque.",
        "Da ieri il bambino è molto irrequieto, non sta fermo un attimo e piange spesso.",
    ],
    "Prurito o bruciore anale o delle aree genitali": [
        "Mia figlia si gratta continuamente nelle parti intime, dice che brucia.",
        "Il bambino si lamenta di un forte prurito nella zona del sederino, soprattutto la notte.",
        "Da qualche giorno la piccola si gratta tantissimo davanti, dice che le brucia quando fa pipì.",
        "Mio figlio dice che gli prude attorno all'anuso, soprattutto dopo aver fatto la cacca.",
    ],
    "Arrossamento o gonfiore anale o delle aree genitali": [
        "La piccola ha tutto il sederino rosso e gonfio, anche attorno alla zona davanti.",
        "Mio figlio ha lo scroto arrossato e leggermente gonfio da ieri.",
        "La bambina ha la zona genitale infiammata, rossa e con un piccolo gonfiore visibile.",
        "Vedo arrossamento attorno all'anuso del piccolo, la pelle è anche un po' gonfia.",
    ],
    "Dolore al ginocchio": [
        "Mio figlio si lamenta di dolore al ginocchio destro da quando ha giocato a calcio ieri.",
        "La bambina piange quando piega il ginocchio sinistro, dice che fa male dietro.",
        "Tommaso ha dolore a entrambe le ginocchia, soprattutto la sera prima di dormire.",
        "L'adolescente si lamenta di dolore al ginocchio sotto la rotula da due settimane.",
    ],
    "Poliuria (emissione di abbondante quantità di urina)": [
        "Mio figlio fa pipì in grandi quantità, devo cambiare il pannolino con doppia capienza.",
        "Da una settimana la bambina urina volumi enormi, riempie il vasino ogni volta.",
        "Il piccolo bagna pannolini pesantissimi, mi sembra urini il triplo del normale.",
        "Mia figlia fa una pipì abbondante a ogni minzione, piscia tantissimo.",
    ],
    "Pollachiuria (necessità di urinare molto spesso ma con piccole quantità)": [
        "La maestra dice che mio figlio chiede di andare in bagno continuamente ma fa pochissima pipì.",
        "Mia figlia corre in bagno ogni 15 minuti, ma poi fa solo qualche goccia.",
        "Il bambino vuole fare pipì in continuazione, però le quantità sono ridicole.",
        "Da ieri Tommaso va al bagno ogni mezz'ora ma fa una pipì minuscola ogni volta.",
    ],
    "Dolore muscolare/Scheletrico": [
        "Mio figlio si lamenta di dolori muscolari diffusi, dice che gli fanno male le gambe e le braccia.",
        "La bambina ha dolore alle ossa, dice che le fanno male le gambe come crescita ma è continuo.",
        "Tommaso lamenta dolori muscolari ovunque, soprattutto cosce e schiena, da quando ha la febbre.",
        "L'adolescente ha dolori scheletrici e muscolari, fatica anche a girarsi nel letto.",
    ],
    "Sincope, collasso": [
        "Mia figlia è svenuta a scuola, è caduta a terra ed è rimasta senza coscienza per qualche secondo.",
        "Il bambino si è alzato di scatto e ha perso i sensi, è collassato sul divano.",
        "Tommaso ha avuto uno svenimento improvviso in palestra, si è afflosciato come un sacco.",
        "L'adolescente è caduto a terra perdendo conoscenza, si è ripreso dopo 30 secondi.",
    ],
    "Vertigini, capogiro": [
        "Mio figlio dice che gli gira la testa quando si alza, deve aggrapparsi al muro.",
        "La bambina barcolla e dice che ha le vertigini, si appoggia ai mobili per camminare.",
        "Tommaso ha capogiri da stamattina, vede tutto girare e si sente svenire.",
        "L'adolescente ha avuto vertigini forti, ha dovuto sedersi perché tutto gli ruotava intorno.",
    ],
    "Dolore articolare": [
        "Mia figlia si lamenta di dolore alle articolazioni, polsi e caviglie soprattutto.",
        "Il bambino ha dolore alle articolazioni delle dita, le tiene piegate e non le vuole muovere.",
        "Tommaso lamenta dolore alle giunture, soprattutto al gomito e alla spalla destra.",
        "L'adolescente ha le articolazioni gonfie e dolenti da tre giorni.",
    ],
    "Dolore dentale": [
        "Mio figlio si tocca un dente in fondo e dice che fa malissimo, non riesce a mordere.",
        "La bambina si lamenta di mal di denti da ieri, indica un molare in alto a sinistra.",
        "Tommaso ha mal di denti forte, soprattutto quando beve qualcosa di freddo.",
        "L'adolescente ha un dolore lancinante a un dente, non riesce a dormire.",
    ],
    "Dolore toracico": [
        "Mio figlio si tocca il petto e dice che ha male qui, soprattutto quando respira.",
        "La bambina lamenta dolore al torace, una fitta sotto la mammella sinistra.",
        "Tommaso ha dolore al petto da stamattina, dice che è uno schiaccio al centro.",
        "L'adolescente si lamenta di dolore toracico che peggiora con i respiri profondi.",
    ],
    "Dolore inguino-genitale": [
        "Mio figlio si lamenta di dolore all'inguine, dice che gli tira quando cammina.",
        "Il bambino ha dolore alla zona genitale e all'inguine destro da ieri sera.",
        "Tommaso piange quando alzo le gambe per cambiarlo, dice che fa male all'inguine.",
        "L'adolescente lamenta dolore in zona inguino-genitale, sembra peggiorare in piedi.",
    ],
    "Enuresi notturna": [
        "Mia figlia di 7 anni continua a fare la pipì a letto ogni notte, anche dopo aver smesso il pannolino.",
        "Il bambino di 8 anni bagna il letto quasi tutte le notti da quando è iniziato l'asilo.",
        "Tommaso ha 6 anni e da qualche mese si bagna nel sonno, prima non succedeva.",
        "L'adolescente ha avuto una ricaduta, sta facendo di nuovo la pipì a letto.",
    ],
    "Irregolarità mestruali": [
        "Mia figlia di 14 anni ha cicli mestruali molto irregolari, salta mesi interi poi ne ha due in uno.",
        "L'adolescente ha il ciclo abbondantissimo che dura 10 giorni, poi salta del tutto.",
        "Da quando ha avuto il primo ciclo le mestruazioni sono saltuarie, ogni 2-3 mesi.",
        "Mia figlia di 13 anni ha ciclo molto irregolare, durata e flusso variabili ogni volta.",
    ],
    "Ansia": [
        "Mia figlia di 10 anni è in uno stato di ansia continua, si mangia le unghie e dice di avere paura.",
        "L'adolescente ha attacchi d'ansia prima della scuola, respiro corto e cuore che batte forte.",
        "Tommaso è angosciato per qualsiasi cosa, dice di sentirsi sempre in allerta.",
        "Il bambino ha ansia da separazione fortissima, piange ogni mattina prima dell'asilo.",
    ],
    "Singhiozzo": [
        "Mio figlio ha il singhiozzo da più di un'ora, non riesce a smettere.",
        "Il piccolo dopo aver poppato fa singhiozzo continuo per molto tempo.",
        "La bambina ha attacchi di singhiozzo lunghissimi, almeno 30 minuti di seguito.",
        "Tommaso ha singhiozzato tutto il pomeriggio senza tregua.",
    ],
    "Tremore": [
        "Mio figlio ha le mani che tremano quando le tende, un tremore fine ma evidente.",
        "Da ieri la bambina ha tremori alle braccia, sembra non riuscire a controllarsi.",
        "Tommaso trema tutto, soprattutto le manine quando prende la forchetta.",
        "L'adolescente ha tremore alle estremità da qualche giorno, soprattutto al risveglio.",
    ],
    "Disturbi della vista": [
        "Mia figlia dice che vede sfocato da stamattina, si avvicina molto agli oggetti.",
        "Il bambino lamenta visione doppia, dice che vede due cose dove ce n'è una.",
        "Tommaso si lamenta che vede male, oggetti offuscati soprattutto da lontano.",
        "L'adolescente ha avuto un episodio in cui non vedeva da un occhio per qualche minuto.",
    ],
    "Zoppìa": [
        "Mio figlio zoppica vistosamente dalla gamba destra da stamattina, non appoggia il piede.",
        "La bambina cammina male, trascina la gamba sinistra e piange se le faccio fare passi.",
        "Tommaso zoppica da ieri sera, non sappiamo perché, non ricorda di essere caduto.",
        "Il piccolo zoppica e dice che gli fa male qualcosa nella gamba quando appoggia il peso.",
    ],
    "Rigonfiamento di una ghiandola": [
        "Sento un rigonfiamento sul collo di mio figlio, una pallina sotto la mandibola.",
        "Mia figlia ha una ghiandola gonfia all'inguine destro, mobile sotto la pelle.",
        "Il bambino ha un linfonodo grosso dietro l'orecchio, è cresciuto in pochi giorni.",
        "Tommaso ha un rigonfiamento al collo lateralmente, una specie di noce sotto la pelle.",
    ],
    "Alitosi": [
        "Mio figlio ha l'alito pesantissimo da una settimana, anche dopo aver lavato i denti.",
        "La bambina ha un fortissimo alito cattivo, sa di marcio.",
        "Tommaso ha l'alito sgradevole da giorni, non capisco da cosa dipenda.",
        "L'alito di mia figlia è cambiato, sa di acetone in modo molto evidente.",
    ],
    "Andatura instabile": [
        "Mio figlio cammina come ubriaco da stamattina, barcolla e non riesce a stare dritto.",
        "La bambina ha un'andatura strana, ondeggia e sembra perdere l'equilibrio.",
        "Tommaso cammina male, instabile, deve appoggiarsi ai mobili per non cadere.",
        "Il piccolo ha iniziato a camminare in modo instabile da ieri, va a destra e a sinistra.",
    ],
    "Ingestione di corpo estraneo": [
        "Ho paura che mio figlio abbia ingoiato una moneta, è scomparsa e lui ha avuto colpi di tosse.",
        "Il bambino ha ingerito una pila bottone, l'ho visto mettersela in bocca.",
        "Mia figlia ha mangiato un pezzo di plastica del giocattolo, non lo trovo più.",
        "Tommaso ha messo in bocca una pallina di carta e l'ha inghiottita davanti a me.",
    ],
    "Ittero": [
        "Mio figlio ha il bianco degli occhi giallastro e anche la pelle del viso sembra gialla.",
        "Il neonato di 5 giorni ha la pelle decisamente gialla, anche le mani.",
        "Da qualche giorno la bambina ha un colorito giallo, soprattutto evidente sul torace.",
        "L'adolescente ha gli occhi ingialliti e la pelle ha un colorito giallastro.",
    ],
    "Lacrimazione eccessiva": [
        "Mia figlia ha l'occhio destro che lacrima continuamente, le scendono le lacrime sulla guancia.",
        "Il bambino ha lacrimazione costante da entrambi gli occhi, gli si bagna sempre la maglietta.",
        "Tommaso da ieri ha l'occhio sinistro che fa lacrime in continuazione.",
        "Il piccolo lacrima moltissimo dall'occhio destro, anche senza piangere.",
    ],
    "Morso o puntura di zecca": [
        "Ho trovato una zecca attaccata sulla schiena di mio figlio dopo la passeggiata in montagna.",
        "Mia figlia ha una zecca conficcata sul cuoio capelluto, è grossa e nera.",
        "Tommaso ha una zecca attaccata dietro al ginocchio, l'ho vista per caso facendo il bagno.",
        "Il piccolo è stato morso da una zecca, la sto guardando ora attaccata sotto l'ascella.",
    ],
    "Pediculosi o infestazione da parassiti cutanei": [
        "Mia figlia ha i pidocchi, ho trovato lendini sui capelli vicino alla nuca.",
        "Il bambino si gratta in testa continuamente, ho visto pidocchi vivi sulla cute.",
        "Tommaso ha pidocchi, ne ho contati almeno cinque tra i capelli.",
        "L'asilo ha segnalato una pediculosi diffusa, mia figlia ha lendini ovunque.",
    ],
    "Prurito cutaneo diffuso": [
        "Da ieri si gratta dappertutto, braccia, pancia, schiena e gambe, ma non vedo bolle.",
        "Mio figlio ha prurito su tutto il corpo da stamattina, non si dà tregua.",
        "La bambina si gratta in continuazione su tronco e arti, non è localizzato.",
        "Tommaso ha un prurito diffuso senza eruzione visibile, peggiora la sera.",
    ],
    "Punture di insetti": [
        "Mia figlia ha tante punture di zanzara sulle gambe, alcune molto gonfie.",
        "Il bambino è stato punto da una vespa al braccio, è gonfio e dolente.",
        "Tommaso ha una puntura grossa al collo, sembra di una zanzara tigre.",
        "Il piccolo ha decine di puntini rossi sulle braccia, sicuramente punture di insetti.",
    ],
    "Sangue nelle feci": [
        "Mia figlia ha trovato sangue nelle feci stamattina, una piccola striscia rossa.",
        "Il bambino ha fatto la cacca con tracce di sangue nero, semi-digerito.",
        "Tommaso ha avuto una scarica con sangue rosso vivo, ne è uscito parecchio.",
        "Aida ha avuto diarrea con striature di sangue rosso, mi preoccupa molto.",
    ],
    "Sangue nelle urine": [
        "Mio figlio ha fatto pipì rossa stamattina, sicuramente sangue nelle urine.",
        "La bambina ha le urine color cola, ha sicuramente sangue dentro.",
        "Tommaso ha visto sangue quando ha fatto pipì, ne è rimasta traccia rossa nel water.",
        "L'adolescente ha urine rosa-rossastre da ieri, anche con piccoli coaguli.",
    ],
    "Terrore notturno": [
        "Mia figlia stanotte si è svegliata urlando con gli occhi sbarrati, non mi riconosceva.",
        "Il bambino ha episodi di terrore notturno, urla disperato senza svegliarsi davvero.",
        "Tommaso si sveglia piangendo e gridando, sembra terrorizzato e non si calma per minuti.",
        "Il piccolo da qualche notte ha pavor nocturnus, urli laceranti senza memoria al mattino.",
    ],
    "Sonniloquio": [
        "Mio figlio parla nel sonno tutte le notti, frasi intere senza senso.",
        "La bambina parla durante il sonno, a volte ride o piange parlando.",
        "Tommaso fa lunghi monologhi mentre dorme, a volte sembra discutere con qualcuno.",
        "Il piccolo parla nel sonno da quando ha cominciato la scuola, ogni notte.",
    ],
    "Risvegli confusionali": [
        "Mio figlio si sveglia confuso, piange ma non risponde alle mie domande, è come perso.",
        "La bambina ha risvegli in cui sembra disorientata, non capisce dove si trovi per dieci minuti.",
        "Tommaso si sveglia frastornato di notte, fissa il vuoto e non riesce a parlare normalmente.",
        "Il piccolo ha episodi di risveglio confuso, mi guarda come se non mi conoscesse.",
    ],
    "Patereccio": [
        "Mio figlio ha l'unghia del pollice infiammata, rossa e gonfia con un po' di pus attorno.",
        "La bambina ha il dito gonfio attorno all'unghia, dice che pulsa e fa male.",
        "Tommaso ha un giradito al pollice, la pelle è arrossata e tesa.",
        "Il piccolo ha un'infezione attorno all'unghia del piede, si sta formando un ascesso.",
    ],
    "Onicomadesi": [
        "A mia figlia si stanno staccando le unghie dei piedi dopo che ha avuto la mano-piede-bocca.",
        "Il bambino ha perso completamente l'unghia del pollice senza traumi.",
        "Tommaso ha le unghie delle mani che si stanno staccando dalla base.",
        "Il piccolo sta perdendo le unghie spontaneamente, già ne ha perse due.",
    ],
    "Micosi dell'unghia": [
        "Mia figlia ha l'unghia dell'alluce ingiallita e ispessita, sembra una micosi.",
        "Il bambino ha le unghie dei piedi che si sgretolano e hanno aspetto giallastro.",
        "Tommaso ha l'unghia del pollice del piede deformata e di colore strano, friabile.",
        "Sospetto una micosi alle unghie dei piedi di mio figlio, sono tutte rovinate e gialle.",
    ],
    "Alterazione cromatica dell'unghia": [
        "Mia figlia ha un'unghia diventata nera dopo essersi schiacciata il dito.",
        "Il bambino ha le unghie con strisce bianche orizzontali, prima non c'erano.",
        "Tommaso ha l'unghia del pollice diventata blu-violacea, dopo un trauma.",
        "Le unghie del piccolo hanno macchie bianche e marroni, mai viste prima.",
    ],
    "Feci molto chiare": [
        "Da due giorni mio figlio fa la cacca chiarissima, quasi color crema.",
        "La bambina ha le feci color argilla, mai viste così chiare.",
        "Tommaso ha fatto una scarica completamente bianca, mi spavento.",
        "Il piccolo sta facendo cacca chiarissima da tre giorni, ho fotografato.",
    ],
    "Pronazione dolorosa dell'avambraccio": [
        "Ho tirato il braccio di mia figlia per non farla cadere e ora non lo muove più, lo tiene molle.",
        "Mio figlio non muove il braccio destro dopo che il fratello l'ha tirato per giocare.",
        "Tommaso non vuole usare l'avambraccio sinistro, lo tiene piegato e piange se lo tocco.",
        "Il piccolo ha il braccio penzolante dopo uno strappo, non lo solleva più.",
    ],
    "Problematiche dell'ombelico": [
        "L'ombelico del neonato esce verso fuori e ha un piccolo gonfiore.",
        "Mio figlio ha dell'umido attorno all'ombelico, sembra rosso.",
        "Il piccolo di 1 mese ha ancora il moncone ombelicale che non si stacca, è rosso.",
        "Vedo una protuberanza all'ombelico della bambina, esce quando piange.",
    ],
    "Ustione o Scottatura solare": [
        "Mia figlia si è scottata la mano sul forno, c'è una bolla grossa.",
        "Il bambino è ustionato sulle spalle dopo il mare, pelle rossissima e tesa.",
        "Tommaso ha rovesciato l'acqua bollente sulla gamba, la pelle è arrossata e dolente.",
        "Il piccolo ha una scottatura sul viso e sulle braccia da troppo sole.",
    ],
    "Problematiche del pene": [
        "Mio figlio ha la punta del pene arrossata e gonfia, fatica a fare pipì.",
        "Il bambino non riesce a scoprire il glande, urla quando ci provo.",
        "Tommaso ha il prepuzio infiammato con secrezione biancastra.",
        "Il piccolo ha il pene con punta rossa e gonfia, sembra fimosi serrata.",
    ],
    "Gonfiore improvviso di volto o labbra": [
        "Mia figlia ha le labbra improvvisamente gonfissime, sembra siano raddoppiate.",
        "Mio figlio ha il viso gonfio, soprattutto attorno agli occhi e alle labbra, comparso in pochi minuti.",
        "Tommaso si è gonfiato all'improvviso in tutto il viso dopo aver mangiato pesce.",
        "Il piccolo ha una palpebra e mezzo labbro gonfio, comparso ora di colpo.",
    ],
    "Ferita o taglio": [
        "Mio figlio si è tagliato il dito con le forbici, sanguina molto.",
        "La bambina è caduta e si è procurata una ferita al ginocchio, è abbastanza profonda.",
        "Tommaso si è ferito alla testa contro lo spigolo, c'è un taglio di 2 cm.",
        "Il piccolo ha un taglio al labbro dopo essere caduto, sanguina e si vede la mucosa interna.",
    ],
    "Trauma arto con gonfiore o deformità": [
        "Mio figlio è caduto dalla bici, il polso è gonfio e sembra storto, non lo muove.",
        "Mia figlia ha il braccio gonfio e deformato dopo essere scivolata, non sopporta nemmeno che lo tocchi.",
        "Tommaso ha la caviglia gonfia come una palla e a forma strana dopo la caduta.",
        "Il piccolo ha il polso fortemente gonfio e visibilmente deformato dopo il trauma.",
    ],
    "Segni di sviluppo puberale anticipato": [
        "Mia figlia di 7 anni sta sviluppando il seno, ho notato due piccoli rigonfiamenti.",
        "Mio figlio di 8 anni ha già peluria nelle parti intime e voce che sta cambiando.",
        "La bambina di 6 anni ha avuto la prima mestruazione, sembra molto presto.",
        "Il piccolo di 7 anni mostra crescita di peli pubici e ingrossamento testicolare.",
    ],
}


# ----------------------------------------------------------------------------
# NEGATIONS: 1 per symptom (gold = [])
# ----------------------------------------------------------------------------
NEGATIONS: dict[str, str] = {
    "Febbre": "Da ieri ha mal di testa e si sente debole ma niente febbre, l'ho misurato tre volte e la temperatura è normale.",
    "Mal di gola": "Tossisce un po' e ha il naso chiuso ma non ha mal di gola, gliel'ho chiesto e dice che non gli fa male a deglutire.",
    "Dolore addominale": "Ha vomitato due volte ma la pancia non gli fa male, l'ho premuta e non si lamenta.",
    "Vomito": "Ha avuto la diarrea per due giorni ma non ha mai vomitato, ha solo nausea.",
    "Diarrea": "Ha vomitato tre volte ma la cacca è normale, niente diarrea.",
    "Difficoltà respiratoria": "Tossisce molto ma respira bene, niente affanno né rumori strani.",
    "Tosse": "Ha la febbre e il raffreddore ma non tossisce affatto, nemmeno di notte.",
    "Naso ostruito o che cola": "Ha mal di gola e tossisce ma il naso è completamente libero, non cola e non è chiuso.",
    "Mal di orecchio": "Ha il raffreddore forte ma le orecchie non gli fanno male, gliel'ho chiesto più volte.",
    "Occhio rosso": "Ha gli occhi che lacrimano un po' ma non sono affatto rossi.",
    "Secrezioni oculari": "Ha gli occhi un po' arrossati ma niente pus o sostanze, sono asciutti.",
    "Occhio gonfio": "Ha l'occhio rosso ma le palpebre non sono gonfie, è tutto normale come forma.",
    "Trauma cranico": "È caduto dal letto ma non ha battuto la testa, è caduto sul sedere.",
    "Mal di testa": "Ha vomitato e ha la febbre ma non si lamenta di mal di testa, dice che la testa sta bene.",
    "Lesioni cutanee": "Ha la febbre ma sulla pelle non è uscito niente, nessuna macchia o bollicina.",
    "Dolore all'occhio": "Ha l'occhio rosso e lacrima ma dice che non gli fa male, non ha dolore.",
    "Ingestione sostanza tossica": "Ha vomitato ma non ha ingerito niente di strano, ha solo l'influenza.",
    "Stipsi": "Ha la diarrea da due giorni, di sicuro non è stitico.",
    "Dolore o bruciore nella minzione": "Fa pipì spesso ma non si lamenta di bruciore, dice che non gli fa male.",
    "Insonnia": "Si addormenta subito la sera, niente difficoltà a prendere sonno, dorme tranquillo per ore.",
    "Risvegli notturni": "Dorme tutta la notte filata, non si sveglia mai, è solo stanco di giorno.",
    "Russamento nel sonno": "Dorme con il naso chiuso ma non russa, lo controllo tutte le notti.",
    "Sonnambulismo": "Parla un po' nel sonno ma non si è mai alzato dal letto, non cammina dormendo.",
    "Apnee nel sonno": "Russa forte ma il respiro è regolare, non ho mai notato pause di respiro.",
    "Bruxismo": "Stringe le mani nel sonno ma non digrigna i denti, sento solo il respiro.",
    "Inappetenza": "Mangia normalmente, anzi forse più del solito, l'appetito è ottimo.",
    "Iperfagia": "Mangia poco ma è normale per lui, di sicuro non ha fame eccessiva.",
    "Polidipsia": "Beve come al solito, non ha sete più del normale.",
    "Convulsioni": "Ha tremato un po' per il freddo ma non ha avuto convulsioni, era cosciente tutto il tempo.",
    "Nausea": "Ha mal di pancia ma niente nausea, mangia tranquillo.",
    "Lesioni del cavo orale": "Ha mal di gola ma in bocca è tutto pulito, niente afte o macchie.",
    "Sanguinamento dal naso": "Ha il naso chiuso ma non ha mai perso sangue, niente epistassi.",
    "Irrequietezza o pianto inconsolabile": "Piange un po' ma si calma subito col ciuccio, non è inconsolabile.",
    "Prurito o bruciore anale o delle aree genitali": "Si gratta un po' la testa ma niente prurito sotto, le parti intime stanno bene.",
    "Arrossamento o gonfiore anale o delle aree genitali": "Ha la pelle un po' irritata sulla pancia ma le parti intime sono normali, niente arrossamento.",
    "Dolore al ginocchio": "Ha dolore alla caviglia ma il ginocchio è perfetto, lo piega senza problemi.",
    "Poliuria (emissione di abbondante quantità di urina)": "Fa pipì poche volte e quantità normali, non urina troppo.",
    "Pollachiuria (necessità di urinare molto spesso ma con piccole quantità)": "Va in bagno solo 4-5 volte al giorno e fa quantità normali, niente di insolito.",
    "Dolore muscolare/Scheletrico": "Ha la febbre ma non ha dolori ai muscoli o alle ossa, dice che il corpo non gli fa male.",
    "Sincope, collasso": "Ha avuto le vertigini ma non è mai svenuto, ha sempre mantenuto coscienza.",
    "Vertigini, capogiro": "Ha mal di testa ma niente vertigini, cammina dritto senza barcollare.",
    "Dolore articolare": "Ha dolori muscolari ma le articolazioni stanno bene, le muove tutte senza problemi.",
    "Dolore dentale": "Ha mal di gola ma i denti non gli fanno male, mastica tranquillo.",
    "Dolore toracico": "Tossisce molto ma il petto non gli fa male, dice che non sente dolore lì.",
    "Dolore inguino-genitale": "Ha mal di pancia in alto ma niente dolore all'inguine o alle parti intime.",
    "Enuresi notturna": "Dorme tutta la notte all'asciutto, non bagna mai il letto.",
    "Irregolarità mestruali": "Ha cicli regolari ogni 28 giorni esatti, mai un ritardo.",
    "Ansia": "È un bambino sereno, non ha ansie particolari, va a scuola contento.",
    "Singhiozzo": "Ha la nausea ma niente singhiozzo, il respiro è regolare.",
    "Tremore": "Ha la febbre alta ma non trema, le mani sono ferme.",
    "Disturbi della vista": "Ha mal di testa ma vede benissimo, lo controllo facendogli leggere da lontano.",
    "Zoppìa": "Si lamenta della gamba ma cammina perfettamente, non zoppica per niente.",
    "Rigonfiamento di una ghiandola": "Ha mal di gola ma le ghiandole del collo sono normali, le ho palpate.",
    "Alitosi": "Ha mal di gola ma l'alito è normale, sa di niente.",
    "Andatura instabile": "Ha le vertigini al risveglio ma cammina dritto, equilibrio perfetto.",
    "Ingestione di corpo estraneo": "Ho avuto paura ma non ha mangiato la pila, l'ho ritrovata sotto il divano.",
    "Ittero": "È pallido ma non giallo, occhi e pelle hanno colorito normale.",
    "Lacrimazione eccessiva": "Ha l'occhio rosso ma non lacrima, è asciutto.",
    "Morso o puntura di zecca": "Siamo stati in montagna ma l'ho controllato tutto, nessuna zecca attaccata.",
    "Pediculosi o infestazione da parassiti cutanei": "Si gratta la testa per il caldo, ho controllato e non ci sono pidocchi né lendini.",
    "Prurito cutaneo diffuso": "Si gratta solo dietro al ginocchio, niente prurito generalizzato.",
    "Punture di insetti": "Ha qualche puntino rosso ma non sono punture di insetti, è una dermatite.",
    "Sangue nelle feci": "Ha avuto la diarrea ma le feci erano marroni normali, niente sangue.",
    "Sangue nelle urine": "Fa pipì un po' scura per il caldo ma non c'è sangue, è solo concentrata.",
    "Terrore notturno": "Si sveglia di notte ma è tranquillo, niente urla né pavor.",
    "Sonniloquio": "Dorme silenzioso, non parla mai durante la notte.",
    "Risvegli confusionali": "Si sveglia perfettamente lucido, mi riconosce subito.",
    "Patereccio": "Ha un graffio sul dito ma niente infiammazione attorno all'unghia.",
    "Onicomadesi": "Le unghie sono attaccate normalmente, nessuna sta cadendo.",
    "Micosi dell'unghia": "Le unghie sono integre, niente ispessimenti né colorazioni anomale.",
    "Alterazione cromatica dell'unghia": "Le unghie sono di colore normale, rosa pallido come sempre.",
    "Feci molto chiare": "Le feci sono marroni come al solito, colore normale.",
    "Pronazione dolorosa dell'avambraccio": "Ho tirato il braccio per non farlo cadere ma lo muove tranquillamente, nessun problema.",
    "Problematiche dell'ombelico": "L'ombelico del neonato è guarito perfettamente, niente arrossamenti o secrezioni.",
    "Ustione o Scottatura solare": "Siamo stati al mare ma con crema 50, nessuna scottatura, pelle integra.",
    "Problematiche del pene": "Il pene è normale, niente arrossamento, secrezione o gonfiore.",
    "Gonfiore improvviso di volto o labbra": "Ha mangiato fragole ma niente reazione, viso e labbra normali.",
    "Ferita o taglio": "È caduto ma non si è ferito, nessun taglio né escoriazione.",
    "Trauma arto con gonfiore o deformità": "È caduto dalla bici ma il braccio è perfetto, nessun gonfiore o deformità.",
    "Segni di sviluppo puberale anticipato": "La bambina di 7 anni ha sviluppo normale, niente seno né peli.",
}


# ----------------------------------------------------------------------------
# PAST_RESOLVED: explicitly past/resolved (gold = [])
# ----------------------------------------------------------------------------
PAST_RESOLVED: list[tuple[str, str]] = [
    ("La febbre la settimana scorsa è passata da giorni, ora chiamo solo per il certificato.", "Febbre"),
    ("La tosse di settimana scorsa per fortuna è finita, ora sta bene.", "Tosse"),
    ("Aveva mal di pancia ieri ma stamattina si è svegliato sereno e ha già fatto colazione.", "Dolore addominale"),
    ("Il vomito di due giorni fa è passato, ora mangia regolarmente.", "Vomito"),
    ("La diarrea della settimana scorsa è guarita completamente, feci normali da 3 giorni.", "Diarrea"),
    ("Il mal di gola di sabato è passato del tutto, oggi vuole tornare a scuola.", "Mal di gola"),
    ("L'occhio rosso di ieri è completamente guarito stamattina.", "Occhio rosso"),
    ("Aveva la congiuntivite ma le secrezioni sono finite con il collirio.", "Secrezioni oculari"),
    ("Il mal di testa di ieri sera con la tachipirina è passato, oggi sta bene.", "Mal di testa"),
    ("Il mal d'orecchio è passato dopo l'antibiotico, ora non si lamenta più.", "Mal di orecchio"),
    ("La stitichezza è risolta, finalmente ha fatto la cacca normalmente.", "Stipsi"),
    ("Le scariche con sangue sono cessate due giorni fa, ora le feci sono pulite.", "Sangue nelle feci"),
    ("Il bruciore quando faceva pipì è passato, ora urina senza dolore.", "Dolore o bruciore nella minzione"),
    ("Aveva il raffreddore forte la settimana scorsa, ora il naso è libero.", "Naso ostruito o che cola"),
    ("Era zoppicante ieri ma stamattina cammina perfettamente.", "Zoppìa"),
    ("Le punture di zanzara sono guarite, niente più gonfiori.", "Punture di insetti"),
    ("La scottatura solare di domenica è già pelata, ora la pelle sta bene.", "Ustione o Scottatura solare"),
    ("Il taglio al ginocchio è cicatrizzato, niente più crosta.", "Ferita o taglio"),
    ("Aveva le vertigini stamattina ma ora sono passate del tutto.", "Vertigini, capogiro"),
    ("Le convulsioni febbrili sono finite, sta bene da ieri sera.", "Convulsioni"),
    ("Il sangue dal naso si è fermato dopo 5 minuti e non si è più ripetuto.", "Sanguinamento dal naso"),
    ("La nausea di ieri è passata, oggi ha mangiato normalmente.", "Nausea"),
    ("Il dolore al ginocchio dopo la partita è completamente sparito.", "Dolore al ginocchio"),
    ("L'episodio di pianto inconsolabile è terminato dopo qualche ora, ora dorme tranquillo.", "Irrequietezza o pianto inconsolabile"),
    ("Il mal di denti è passato dopo la visita dal dentista.", "Dolore dentale"),
    ("La pediculosi è risolta dopo i trattamenti, niente più pidocchi da una settimana.", "Pediculosi o infestazione da parassiti cutanei"),
    ("Le afte in bocca sono guarite, oggi mangia tranquillo.", "Lesioni del cavo orale"),
    ("Il prurito diffuso di ieri è scomparso, oggi è sereno.", "Prurito cutaneo diffuso"),
    ("La zecca l'ho tolta tre giorni fa e la pelle attorno è pulita.", "Morso o puntura di zecca"),
    ("Lo svenimento di sabato non si è più ripetuto, sta bene.", "Sincope, collasso"),
    ("L'eruzione cutanea della varicella si è risolta tutta in croste cadute.", "Lesioni cutanee"),
    ("Il singhiozzo è passato dopo un po' d'acqua, niente più.", "Singhiozzo"),
    ("L'enuresi è stata risolta da mesi, dorme asciutto da settimane.", "Enuresi notturna"),
    ("L'episodio di tremore di ieri sera è terminato dopo pochi minuti.", "Tremore"),
    ("Il giradito al pollice è guarito completamente.", "Patereccio"),
    ("L'unghia caduta è già ricresciuta normalmente.", "Onicomadesi"),
    ("Il rigonfiamento al collo è scomparso, linfonodi tornati normali.", "Rigonfiamento di una ghiandola"),
    ("L'andatura instabile dopo l'otite è completamente recuperata.", "Andatura instabile"),
    ("Il gonfiore al labbro per l'allergia è sparito con l'antistaminico.", "Gonfiore improvviso di volto o labbra"),
    ("La pronazione l'ha sistemata il pediatra ieri, ora muove il braccio normalmente.", "Pronazione dolorosa dell'avambraccio"),
]


# ----------------------------------------------------------------------------
# MULTI: multi-symptom messages (gold = list of canonical labels)
# ----------------------------------------------------------------------------
MULTI: list[tuple[str, list[str]]] = [
    ("Da ieri sera ha 39 di febbre, mal di gola fortissimo e tossisce in continuazione.",
     ["Febbre", "Mal di gola", "Tosse"]),
    ("Mio figlio ha la febbre, il naso colante e una tosse insistente, sembra l'influenza.",
     ["Febbre", "Naso ostruito o che cola", "Tosse"]),
    ("Ha vomitato 4 volte e ha la diarrea liquida da stamattina, comincia ad essere debole.",
     ["Vomito", "Diarrea"]),
    ("La piccola ha 38.5, vomita ogni cosa che beve e ha scariche di diarrea continue.",
     ["Febbre", "Vomito", "Diarrea"]),
    ("Si tiene la pancia e ha già vomitato due volte, dolori a ondate.",
     ["Dolore addominale", "Vomito"]),
    ("È caduto dalla bici, ha battuto la testa e ora si lamenta di mal di testa fortissimo.",
     ["Trauma cranico", "Mal di testa"]),
    ("Zoppica vistosamente e dice che il ginocchio destro gli fa molto male.",
     ["Zoppìa", "Dolore al ginocchio"]),
    ("Tossisce continuamente e quando respira sento un fischio, fa proprio fatica.",
     ["Tosse", "Difficoltà respiratoria"]),
    ("Si lamenta di dolore al petto e fa fatica a respirare, sembra ansimare.",
     ["Dolore toracico", "Difficoltà respiratoria"]),
    ("Russa fortissimo ogni notte e a volte si ferma proprio di respirare per qualche secondo.",
     ["Russamento nel sonno", "Apnee nel sonno"]),
    ("Non si addormenta la sera e poi si sveglia 3-4 volte durante la notte.",
     ["Insonnia", "Risvegli notturni"]),
    ("Beve quantità enormi di acqua e fa pipì abbondantissima, mai vista così.",
     ["Polidipsia", "Poliuria (emissione di abbondante quantità di urina)"]),
    ("Non vuole mangiare niente e ha sempre la nausea, è pallida e abbattuta.",
     ["Inappetenza", "Nausea"]),
    ("Ha l'occhio destro tutto rosso e gli esce pus giallo, anche la palpebra è incollata al risveglio.",
     ["Occhio rosso", "Secrezioni oculari"]),
    ("Ha mal d'orecchio fortissimo e febbre alta da ieri sera.",
     ["Mal di orecchio", "Febbre"]),
    ("Sono uscite tante macchioline rosse su tutto il corpo e si gratta in continuazione.",
     ["Lesioni cutanee", "Prurito cutaneo diffuso"]),
    ("Fa la pipì rossa ed è bruciante quando va in bagno, piange ogni volta.",
     ["Sangue nelle urine", "Dolore o bruciore nella minzione"]),
    ("Mal di testa fortissimo e ha già vomitato due volte, vuole stare al buio.",
     ["Mal di testa", "Vomito"]),
    ("Ha tantissima tosse e quando tossisce forte gli esce un po' di sangue dal naso.",
     ["Tosse", "Sanguinamento dal naso"]),
    ("Aveva 39.8 di febbre e ha avuto un episodio di scosse a tutto il corpo, una crisi convulsiva.",
     ["Febbre", "Convulsioni"]),
    ("Ha mal di pancia, vomita e ha la diarrea, sembra una gastroenterite.",
     ["Dolore addominale", "Vomito", "Diarrea"]),
    ("Russa ma stanotte ho notato lunghe pause nel respiro e poi sussulti.",
     ["Russamento nel sonno", "Apnee nel sonno"]),
    ("Ha l'occhio gonfio, lacrima molto e si lamenta che le fa male.",
     ["Occhio gonfio", "Lacrimazione eccessiva", "Dolore all'occhio"]),
    ("Ha sempre fame, beve litri d'acqua e fa pipì in quantità enormi.",
     ["Iperfagia", "Polidipsia", "Poliuria (emissione di abbondante quantità di urina)"]),
    ("Si sveglia di soprassalto urlando, sembra terrorizzata, e poi cammina nel sonno per la stanza.",
     ["Terrore notturno", "Sonnambulismo"]),
]


def all_records():
    """Iterator yielding (case_type, message, gold_list, extras_dict)."""
    for symptom, msgs in POSITIVES.items():
        for m in msgs:
            yield ("positive", m, [symptom], {})
    for symptom, msg in NEGATIONS.items():
        yield ("negation", msg, [], {"negated_symptom": symptom})
    for msg, symptom in PAST_RESOLVED:
        yield ("past_resolved", msg, [], {"resolved_symptom": symptom})
    for msg, syms in MULTI:
        yield ("multi_symptom", msg, list(syms), {})
